<a href="https://colab.research.google.com/github/madhumithadasarathy/CODSOFT/blob/main/fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing necessary libraries

In [117]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the datasets

In [118]:
train_df = pd.read_csv("/content/fraudTrain.csv")
test_df = pd.read_csv("/content/fraudTest.csv")
# Seperating numeric values
train_num_df = train_df.select_dtypes(include='number')
test_num_df = test_df.select_dtypes(include='number')
#Splitting the datasets into training and testing sets
X_train = train_num_df.drop(['is_fraud'],axis=1)
y_train = train_num_df['is_fraud']
X_test = test_num_df.drop(['is_fraud'],axis=1)
y_test = test_num_df['is_fraud']

# Scaling the data

In [119]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# Imputing the missing values in the data

In [120]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="mean")
X_train = imputer.fit_transform(X_train)
X_train = X_train[~np.isnan(X_train).any(axis=1)]
y_train = y_train.dropna()

#Ensuring that the X_train and y_train contain consistent number of samples

In [123]:
print("X_train shape = ",X_train.shape)
print("y_train shape = ",y_train.shape)
X_train = np.delete(X_train,0,axis=0)
print("X_train shape = ",X_train.shape)

X_train shape =  (1292950, 10)
y_train shape =  (1292949,)
X_train shape =  (1292949, 10)


#Building the Logistic Regression Model

In [124]:
from sklearn.linear_model import LogisticRegression
cls = LogisticRegression(random_state=42)
cls.fit(X_train,y_train)

LogisticRegression(random_state=42)

#Predicting values

In [125]:
y_pred_train = cls.predict(X_train)
y_pred_test = cls.predict(X_test)

In [126]:
y_pred_train

array([0., 0., 0., ..., 0., 0., 0.])

In [127]:
y_pred_test

array([0., 0., 0., ..., 0., 0., 0.])

#Evaluating the model's performance

In [128]:
from sklearn.metrics import confusion_matrix, accuracy_score, r2_score
cm = confusion_matrix(y_test,y_pred_test)
cm

array([[553574,      0],
       [  2145,      0]])

In [129]:
accuracy_score(y_test,y_pred_test)

0.9961401355721147